language: node_js
node_js:
  - 10

cache: yarn

env:
 - FIRESTORE_EMULATOR_HOST=localhost:8080 NODE_ENV=test

before_install:
  - cd functions

install:
  - yarn
  - yarn global add firebase-tools
  - firebase setup:emulators:firestore

before_script:
  - firebase emulators:start --only firestore &
  - yarn run build || true
  - yarn run build

script:
  - yarn workspaces run test
