language: node_js
node_js:
- 10
cache: yarn
env:
- FIRESTORE_EMULATOR_HOST=localhost:8080 NODE_ENV=test
before_install:
- cd functions
install:
- yarn
- yarn run setup-emulator-firestore
before_script:
- yarn run emulator-firestore &
- yarn run build
script:
- yarn workspaces run test
before_deploy:
- rm -rf node_modules
- cd ..
deploy:
  provider: firebase
  token:
    secure: ThDJZbtCA71fF09fM/rO02My9CNB/IIZEuFoKR82gjdrTtaUBYStbScSVPe8QhqdarxpM+KMcoDHKD+LdOYtHJFsrRLfDQc0pBBPnb0N8U1y27fwGx9nJ9joh/wSLeVZqaFvHG+ZV7Hb7GZV+57VqQRQzMS6pXedMSPyDgD26LtO8iUlmR3uZRrXieYmXjxy2ix2WJpC4eTXtQLCBhCkGr1eV7Y/6VK+mq/EjlayGdg9RXYPyI8Ghyk5L83TNXklk2f94F1IsEFekI0xwI2YHoS8zU7LdZvrV4RgvOu/iGZ2C09tl6jKbq8UrMSVo9duJa2wShCIxEkDLAEA1E3vdmsy3EXPEfTNn5ee45CCvfNKphpA5Qg7PuUTioxZTdX/yIxxDa0SpEH12tJzzqEjcNQZ/E3jdgqT9XsCO9027J2zKxYZs+g/+lwKTuXjAyLbsrWZEeaLoV3qP+ceHrLSIQTNf1Fmg1vd1zQGaYHJs5njYU/AUhijkaRxBvnBsVy+SXx7FoQGxkcxOybKjn1A7arC0bNTPo1eZxzQ2hucOJTVk9t1ulL9NSQAEWLBMX5u6TWUge2fcPKZmtXlIZc0U7QSna2xvYMksF0QGXonwty9Ije2atTzeh9LtMz87/5sbuYLm3whMR7meJc7nnMNwKS79gSa+WWWjB0uJG9sviI=
