language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_eb816146df40_key -iv $encrypted_eb816146df40_iv
  -in school-api-265018-0ae0e4cd0267.json.enc -out school-api-265018-0ae0e4cd0267.json
  -d
env:
  global:
  - NODE_ENV=ci
