language: node_js

node_js:
- 10

cache: yarn

env:
- FIRESTORE_EMULATOR_HOST=localhost:8080 NODE_ENV=test

before_install:
- cd functions

install:
- yarn
- yarn global add firebase-tools
- yarn global add typescript
- firebase setup:emulators:firestore

before_script:
- firebase emulators:start --only firestore &
- yarn run build || true
- yarn run build

script:
- yarn workspaces run test

before_deploy:
- 'cd ..'

deploy:
  provider: firebase
  token:
    secure: HxKbOgAci/L3MfX68HreH9PPPVX+QwjMgwenD1mSNPNhgHzPOryr8GGR+LpFHr96gXq+xOJC1+y0bg9B6wt3FZSXxQklLEN3au6gollEJ6ik1QopMG0aEiVooEa3hYLaSrfwEy+aMifcZTNWHhv2MT9FYARsuijlu2WLmE4n/s1zqQWAp2FIdF4nApQu2Y7KbKdZvFyXDruoakBiD4V9JlYe0oBS34yEt8+XrtJ/XpRQMgoD1xtiikcyIFUxxGj+rPAbOpm5iv5aLZUmoV3jaSdD/xSOCG93CSBLRAkcSLn8Z/g/ZgDYvYdQ4M5HJQrYkfcWm/I/KR4+Bn0x7jpB2zIBY7Nbz23Kw4wpu2xpQIcnkT0lRIlqSX5ommQBd37Mj6BhQAoTFPytiPHh/Ifbwz/dyorDSn4kTY8HvsOb2Uy2Nd9zBPYuncTA/ahTzUBSGbkkHQZp6MyAd16f45VO+RYk3hP1otYpwyddWJOCg0E5SNoUwA3aszN/gPxQ/prPdYemTpkuN8rZrENrZTB/+NeZjzgd9jofPXH8Mn6omCcbCYngWzY0lsR0wsT36yAJOVN1k37mi+nxj1VIBzevy8A03wuqsdR7SJLgZ9A6Ah6yV8DZ3XV4NyuoZqUbF0ZN8QSVzfg8WgrFKmMRsu4uqWpmSmXvX1yM1RaBuiWqpg0=
