language: node_js
node_js:
  - 10

cache: yarn

env:
 - FIRESTORE_EMULATOR_HOST=localhost:8080 NODE_ENV=test

before_install:
  - cd functions

install:
  - yarn
  - firebase setup:emulators:firestore

after_install:
  - yarn run build

before_script:
  - firebase emulators:start --only firestore &

script:
  - yarn workspaces run test
