language: node_js
node_js:
  - 10

cache: yarn

before_install:
  - cd functions

install:
  - yarn

after_install:
  - firebase setup:emulators:firestore
  - yarn run build

before_script:
  - firebase emulators:start --only firestore &
  - cd package-school-menu

script:
  - yarn workspaces run test
