language: node_js
node_js:
- stable
env:
  global:
    secure: MFktPO2fdG/NH9bJAYqIkU8YLDiKLJh6IR+U1cmOa9Vf2EfWBiE/7AAi5f5SxdL57P9Gj2giRjrZyLAsYCYAa5r/+XuH39PFnFvrf/Y322vvLXJiVwP6f/CU8z1iO8vrj4qgz9JsvIfuija/2jTT1JPUi7vBwJccwVNy3/azISu8wrnVZmAgVN8cI0rsGaUZSWoqk8XwFS704/MtLfkWHstYWahO3AZL1e3XDjHEnSCJ7yaYWpPLO7TrAQGgieyUcqxoPGCxZiqgR5sgg45DSaKFxb7ttNTdm2To61x1xv1a8dRIXMbNibVV9K3Youi2TWywTx9z6VqLCDFhacNamFTiYox7LIeoPT9Gfqt1F47cF+lTTXHD5VhYYs8jYP7w7fbO0rd1Ok3lnYdEHGLcw9cuuKcB8RghTqsrFf0mx7Oh//DlGgwmaRNYxXz/QyqoTzUs2H2IiRWOPtL5NZ3G5W5SBuBpsadl5WNwoYy77WOJ1wfd0hU4VSSAgLQcvJritTfglaLpbyeLXYOIwOpQO9JuqGQ9NiXMYT/rZ5ISfnmoJ7lAPUFQQ9VuNDyfcSGMtiAskW1erOWF7P4z/2J7dm34uYycASUzrq2gsaHecLRY3woJvlhGZPefAfWvBVqqe99oO6pRfugFlPXDQvC1AZu64FIDxDn1sJy/1s+YY6s=
