name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      wd: ./functions

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.wd }}

      - name: Build
        run: 'npm run build:function'
        working-directory: ${{ env.wd }}

      - name: Run test
        run: npm run test
        working-directory: ${{ env.wd }}
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          NODE_ENV: ci
          NODE_TLS_REJECT_UNAUTHORIZED: 0
