name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      wd: ./functions


    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and Firestore emulator
        run: |
          npm i
          npm run setup-emulator-firestore
        working-directory: ${{ env.wd }}

      - name: Run Firestore emulator
        run: npm run emulator-firestore &
        working-directory: ${{ env.wd }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.wd }}

      - name: Run test
        run: npm run test --workspaces
        working-directory: ${{ env.wd }}
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          NODE_ENV: ci
