name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      wd: ./functions

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.wd }}

      - name: Build
        run: 'pnpm run build:function'
        working-directory: ${{ env.wd }}

      - name: Run test
        run: pnpm run test
        working-directory: ${{ env.wd }}
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          NODE_ENV: ci
          NODE_TLS_REJECT_UNAUTHORIZED: 0
