name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      wd: ./functions

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: ${{ env.wd }}
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.wd }}

      - name: Build
        run: pnpm run build --filter @school-api/function
        working-directory: ${{ env.wd }}

      - name: Run tests
        run: pnpm run test:all
        working-directory: ${{ env.wd }}
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          NODE_ENV: ci
          NODE_TLS_REJECT_UNAUTHORIZED: 0
